"""Metadata gerakan berbahasa Indonesia untuk katalog ilustrasi.

Berkas ini adalah SUMBER TUNGGAL KEBENARAN yang ditulis manual: nama Indonesia,
alias yang dipakai untuk pendeteksian, pola gerak, langkah pelaksanaan, dan
poin kunci keselamatan. Bagian yang bersifat data (kelompok otot, alat, dan
berkas gambar) diisi otomatis oleh `scripts/siapkan_gerakan.py` dari basis data
free-exercise-db.

Aturan penulisan alias:
- tulis dalam huruf kecil dan tanpa tanda hubung (normalisasi menyamakan
  "push-up", "push up", dan "pushup" menjadi bentuk yang sama);
- hindari kata yang terlalu umum berdiri sendiri (mis. "row", "press", "squat"
  saja) kecuali memang nama gerakan bakunya, sebab dapat salah tangkap;
- alias yang lebih panjang otomatis diprioritaskan saat pencocokan, sehingga
  "romanian deadlift" tidak akan tertangkap sebagai "deadlift".
"""

from __future__ import annotations

# (id, nama_sumber_free_exercise_db, nama_tampil, nama_indonesia, pola_gerak,
#  alias, langkah, poin_kunci)
GERAKAN: list[dict] = [
    # ------------------------------------------------------------------ TUNGKAI
    {
        "id": "squat",
        "sumber_nama": "Barbell Squat",
        "nama": "Barbell Back Squat",
        "nama_id": "Squat dengan barbel di punggung",
        "pola_gerak": "dominan lutut",
        "alias": ["barbell back squat", "back squat", "barbell squat", "squat barbel", "squat"],
        "langkah": [
            "Letakkan barbel di otot punggung atas, tepat di bawah tulang leher yang menonjol, lalu berdiri dengan kaki selebar bahu dan ujung kaki sedikit menghadap keluar.",
            "Tarik napas, kencangkan otot perut, lalu turun dengan menekuk pinggul dan lutut secara bersamaan seolah hendak duduk.",
            "Turun sampai paha minimal sejajar lantai, sambil menjaga dada tetap terangkat dan punggung dalam posisi netral.",
            "Dorong lantai memakai seluruh telapak kaki sampai kembali berdiri tegak, lalu buang napas di bagian akhir gerakan.",
        ],
        "poin_kunci": "Arahkan lutut mengikuti arah ujung kaki dan jangan biarkan punggung membulat saat naik.",
    },
    {
        "id": "front_squat",
        "sumber_nama": "Front Squat (Clean Grip)",
        "nama": "Front Squat",
        "nama_id": "Squat dengan barbel di depan bahu",
        "pola_gerak": "dominan lutut",
        "alias": ["front squat", "squat depan"],
        "langkah": [
            "Sandarkan barbel pada bagian depan bahu, angkat kedua siku tinggi sampai lengan atas hampir sejajar lantai.",
            "Berdiri dengan kaki selebar bahu, tarik napas, dan kencangkan otot perut.",
            "Turun lurus ke bawah dengan menjaga badan tetap tegak dan siku tetap tinggi.",
            "Dorong lantai sampai berdiri kembali tanpa membiarkan siku turun.",
        ],
        "poin_kunci": "Siku yang turun membuat barbel meluncur ke depan; jaga siku tetap tinggi sepanjang gerakan.",
    },
    {
        "id": "goblet_squat",
        "sumber_nama": "Goblet Squat",
        "nama": "Goblet Squat",
        "nama_id": "Squat dengan beban dipeluk di dada",
        "pola_gerak": "dominan lutut",
        "alias": ["goblet squat"],
        "langkah": [
            "Pegang satu dumbel atau kettlebell dengan kedua tangan, tahan di depan dada.",
            "Berdiri dengan kaki sedikit lebih lebar dari bahu.",
            "Turun sampai siku berada di sisi dalam lutut, jaga badan tetap tegak.",
            "Dorong lantai untuk kembali berdiri sambil menjaga beban tetap menempel di dada.",
        ],
        "poin_kunci": "Cocok sebagai gerakan pengantar sebelum barbell squat karena beban di depan membantu badan tetap tegak.",
    },
    {
        "id": "bodyweight_squat",
        "sumber_nama": "Bodyweight Squat",
        "nama": "Bodyweight Squat",
        "nama_id": "Squat tanpa beban",
        "pola_gerak": "dominan lutut",
        "alias": ["bodyweight squat", "air squat", "squat tanpa beban", "squat berat badan"],
        "langkah": [
            "Berdiri dengan kaki selebar bahu dan kedua tangan lurus ke depan sebagai penyeimbang.",
            "Tarik napas, lalu turun dengan menekuk pinggul dan lutut bersamaan.",
            "Turun sejauh yang masih terasa nyaman tanpa punggung membulat.",
            "Dorong lantai untuk kembali berdiri, buang napas di bagian akhir.",
        ],
        "poin_kunci": "Pakai variasi ini untuk melatih pola gerak dan pemanasan sebelum menambah beban.",
    },
    {
        "id": "leg_press",
        "sumber_nama": "Leg Press",
        "nama": "Leg Press",
        "nama_id": "Menekan beban dengan kaki di mesin",
        "pola_gerak": "dominan lutut",
        "alias": ["leg press", "mesin leg press"],
        "langkah": [
            "Duduk di mesin dan tempelkan seluruh punggung serta pinggul pada sandaran.",
            "Letakkan telapak kaki selebar bahu di tengah papan pijakan.",
            "Lepas pengunci, lalu turunkan beban perlahan sampai lutut menekuk kira-kira sembilan puluh derajat.",
            "Dorong papan kembali tanpa mengunci lutut sepenuhnya di posisi akhir.",
        ],
        "poin_kunci": "Jangan biarkan pinggul terangkat dari sandaran saat beban diturunkan, sebab punggung bawah akan membulat.",
    },
    {
        "id": "hack_squat",
        "sumber_nama": "Hack Squat",
        "nama": "Hack Squat",
        "nama_id": "Squat pada mesin hack",
        "pola_gerak": "dominan lutut",
        "alias": ["hack squat"],
        "langkah": [
            "Masuk ke mesin, sandarkan punggung dan bahu pada bantalan.",
            "Letakkan kaki selebar bahu di tengah pijakan, lalu lepas pengunci.",
            "Turun perlahan sampai paha mendekati sejajar dengan pijakan.",
            "Dorong kembali ke posisi awal tanpa mengunci lutut.",
        ],
        "poin_kunci": "Jalur gerak mesin sudah tetap, jadi fokus pada kedalaman yang nyaman dan tempo yang terkendali.",
    },
    {
        "id": "split_squat",
        "sumber_nama": "Split Squat with Dumbbells",
        "nama": "Split Squat",
        "nama_id": "Squat satu kaki dengan posisi kaki depan-belakang",
        "pola_gerak": "dominan lutut satu kaki",
        "alias": ["split squat", "bulgarian split squat", "split squat dumbel"],
        "langkah": [
            "Berdiri dengan satu kaki di depan dan satu kaki di belakang, jaraknya kira-kira satu langkah panjang.",
            "Pegang dumbel di kedua sisi badan, tegakkan badan.",
            "Turun lurus ke bawah sampai lutut belakang mendekati lantai.",
            "Dorong lantai dengan kaki depan untuk kembali ke posisi awal, selesaikan semua repetisi sebelum berganti kaki.",
        ],
        "poin_kunci": "Turun lurus ke bawah, bukan maju ke depan, agar beban tetap pada kaki depan.",
    },
    {
        "id": "lunge",
        "sumber_nama": "Dumbbell Lunges",
        "nama": "Lunge",
        "nama_id": "Melangkah dan menurunkan badan",
        "pola_gerak": "dominan lutut satu kaki",
        "alias": ["walking lunge", "dumbbell lunge", "lunges", "lunge"],
        "langkah": [
            "Berdiri tegak sambil memegang dumbel di kedua sisi badan.",
            "Melangkah ke depan satu langkah panjang dengan satu kaki.",
            "Turunkan badan sampai kedua lutut menekuk kira-kira sembilan puluh derajat.",
            "Dorong lantai dengan kaki depan untuk kembali berdiri, lalu ulangi dengan kaki yang lain.",
        ],
        "poin_kunci": "Jaga badan tetap tegak; condong ke depan akan memindahkan beban ke punggung bawah.",
    },
    {
        "id": "step_up",
        "sumber_nama": "Dumbbell Step Ups",
        "nama": "Step Up",
        "nama_id": "Naik ke bangku satu kaki",
        "pola_gerak": "dominan lutut satu kaki",
        "alias": ["step up", "step ups"],
        "langkah": [
            "Berdiri menghadap bangku setinggi kira-kira lutut sambil memegang dumbel.",
            "Letakkan satu telapak kaki penuh di atas bangku.",
            "Dorong dengan kaki yang di atas sampai berdiri penuh di bangku.",
            "Turun perlahan dengan kaki yang sama menahan gerakan, lalu ulangi.",
        ],
        "poin_kunci": "Hindari mendorong dengan kaki bawah; tenaga harus datang dari kaki yang berada di atas bangku.",
    },
    {
        "id": "deadlift",
        "sumber_nama": "Barbell Deadlift",
        "nama": "Deadlift",
        "nama_id": "Mengangkat barbel dari lantai",
        "pola_gerak": "dominan pinggul",
        "alias": ["conventional deadlift", "barbell deadlift", "deadlift", "dead lift"],
        "langkah": [
            "Berdiri dengan pertengahan telapak kaki berada di bawah barbel, kaki selebar pinggul.",
            "Tekuk pinggul dan lutut untuk meraih barbel dengan genggaman selebar bahu, jaga punggung tetap lurus dan dada terangkat.",
            "Tarik napas, kencangkan perut, lalu angkat dengan mendorong lantai memakai kaki sambil menegakkan badan; barbel bergerak dekat dengan tulang kering.",
            "Berdiri tegak penuh dengan bahu ditarik ke belakang, lalu turunkan barbel mengikuti jalur yang sama sampai menyentuh lantai.",
        ],
        "poin_kunci": "Punggung wajib tetap lurus dari awal sampai akhir; punggung yang membulat adalah penyebab cedera paling umum pada gerakan ini.",
    },
    {
        "id": "romanian_deadlift",
        "sumber_nama": "Romanian Deadlift",
        "nama": "Romanian Deadlift",
        "nama_id": "Menurunkan barbel dengan pinggul mundur",
        "pola_gerak": "dominan pinggul",
        "alias": ["romanian deadlift", "stiff legged deadlift", "stiff leg deadlift", "rdl"],
        "langkah": [
            "Berdiri tegak memegang barbel di depan paha dengan genggaman selebar bahu.",
            "Tekuk lutut sedikit saja dan pertahankan sudut itu selama gerakan.",
            "Dorong pinggul ke belakang sambil menurunkan barbel menyusuri paha sampai terasa tarikan pada paha belakang.",
            "Dorong pinggul ke depan untuk kembali berdiri tegak.",
        ],
        "poin_kunci": "Gerakan berasal dari pinggul yang mundur, bukan dari punggung yang membungkuk.",
    },
    {
        "id": "hip_thrust",
        "sumber_nama": "Barbell Hip Thrust",
        "nama": "Hip Thrust",
        "nama_id": "Mendorong pinggul ke atas dengan barbel",
        "pola_gerak": "dominan pinggul",
        "alias": ["hip thrust", "barbell hip thrust"],
        "langkah": [
            "Duduk di lantai dengan punggung bagian atas bersandar pada bangku dan barbel di atas lipatan pinggul.",
            "Tekuk lutut dan letakkan telapak kaki rata di lantai selebar pinggul.",
            "Dorong pinggul ke atas sampai badan dari bahu ke lutut membentuk garis lurus.",
            "Tahan sebentar di posisi atas, lalu turunkan pinggul perlahan.",
        ],
        "poin_kunci": "Berhenti di garis lurus; melengkungkan punggung lebih jauh membebani punggung bawah, bukan otot bokong.",
    },
    {
        "id": "glute_bridge",
        "sumber_nama": "Barbell Glute Bridge",
        "nama": "Glute Bridge",
        "nama_id": "Mengangkat pinggul dari posisi telentang",
        "pola_gerak": "dominan pinggul",
        "alias": ["glute bridge", "hip bridge"],
        "langkah": [
            "Berbaring telentang dengan lutut ditekuk dan telapak kaki rata di lantai.",
            "Kencangkan otot perut dan bokong.",
            "Angkat pinggul sampai badan dari bahu ke lutut lurus.",
            "Turunkan pinggul perlahan sampai hampir menyentuh lantai, lalu ulangi.",
        ],
        "poin_kunci": "Gerakan ini sering dipakai sebagai versi ringan sebelum hip thrust berbeban.",
    },
    {
        "id": "leg_curl",
        "sumber_nama": "Lying Leg Curls",
        "nama": "Leg Curl",
        "nama_id": "Menekuk lutut melawan beban",
        "pola_gerak": "isolasi paha belakang",
        "alias": ["lying leg curl", "hamstring curl", "leg curl"],
        "langkah": [
            "Berbaring telungkup di mesin dengan bantalan tepat di atas tumit.",
            "Pegang pegangan mesin dan jaga pinggul tetap menempel pada bantalan.",
            "Tekuk lutut untuk menarik bantalan ke arah bokong.",
            "Turunkan beban perlahan sampai kaki hampir lurus.",
        ],
        "poin_kunci": "Jangan mengangkat pinggul untuk membantu menarik beban.",
    },
    {
        "id": "leg_extension",
        "sumber_nama": "Leg Extensions",
        "nama": "Leg Extension",
        "nama_id": "Meluruskan lutut melawan beban",
        "pola_gerak": "isolasi paha depan",
        "alias": ["leg extension", "leg extensions"],
        "langkah": [
            "Duduk di mesin dan atur bantalan agar berada tepat di atas pergelangan kaki.",
            "Sandarkan punggung dan pegang pegangan di sisi kursi.",
            "Luruskan lutut untuk mengangkat bantalan sampai kaki hampir lurus.",
            "Turunkan beban perlahan sampai kembali ke posisi awal.",
        ],
        "poin_kunci": "Gerakkan beban dengan tempo terkendali, jangan menghentak di posisi lurus.",
    },
    {
        "id": "calf_raise",
        "sumber_nama": "Standing Calf Raises",
        "nama": "Calf Raise",
        "nama_id": "Mengangkat tumit",
        "pola_gerak": "isolasi betis",
        "alias": ["standing calf raise", "calf raise", "calf raises"],
        "langkah": [
            "Berdiri dengan bagian depan telapak kaki di atas pijakan dan tumit menggantung.",
            "Turunkan tumit perlahan sampai terasa tarikan pada betis.",
            "Angkat tumit setinggi mungkin sampai berdiri di ujung kaki.",
            "Tahan sebentar di posisi atas, lalu turunkan lagi dengan terkendali.",
        ],
        "poin_kunci": "Gunakan rentang gerak penuh dari tumit turun sampai ujung kaki agar hasilnya optimal.",
    },
    {
        "id": "back_extension",
        "sumber_nama": "Hyperextensions (Back Extensions)",
        "nama": "Back Extension",
        "nama_id": "Meluruskan badan dari posisi membungkuk",
        "pola_gerak": "penguat punggung bawah",
        "alias": ["back extension", "hyperextension", "hyperextensions", "ekstensi punggung"],
        "langkah": [
            "Atur bantalan alat tepat di lipatan pinggul, lalu kaitkan tumit pada penahan.",
            "Silangkan tangan di dada dan luruskan badan sejajar dengan kaki.",
            "Turunkan badan dengan menekuk pinggul, bukan punggung.",
            "Naikkan badan sampai kembali sejajar, tanpa melengkung berlebihan.",
        ],
        "poin_kunci": "Berhenti di posisi lurus; melengkungkan punggung ke belakang menambah tekanan pada punggung bawah.",
    },
    # ---------------------------------------------------------- DORONG BAGIAN ATAS
    {
        "id": "bench_press",
        "sumber_nama": "Barbell Bench Press - Medium Grip",
        "nama": "Bench Press",
        "nama_id": "Menekan barbel dari dada sambil berbaring",
        "pola_gerak": "dorong horizontal",
        "alias": ["barbell bench press", "flat bench press", "bench press"],
        "langkah": [
            "Berbaring di bangku dengan mata tepat di bawah barbel, telapak kaki rata di lantai.",
            "Genggam barbel sedikit lebih lebar dari bahu, tarik bahu ke belakang dan bawah agar menempel di bangku.",
            "Turunkan barbel dengan terkendali sampai menyentuh bagian tengah dada, siku membentuk sudut sekitar empat puluh lima derajat terhadap badan.",
            "Dorong barbel kembali ke atas sampai lengan hampir lurus, buang napas saat mendorong.",
        ],
        "poin_kunci": "Selalu gunakan pengaman atau bantuan orang lain saat memakai beban berat.",
    },
    {
        "id": "incline_bench_press",
        "sumber_nama": "Barbell Incline Bench Press - Medium Grip",
        "nama": "Incline Bench Press",
        "nama_id": "Menekan barbel pada bangku miring",
        "pola_gerak": "dorong horizontal ke atas",
        "alias": ["incline bench press", "incline barbell press", "incline press"],
        "langkah": [
            "Atur bangku pada kemiringan sekitar tiga puluh derajat, lalu berbaring dengan punggung menempel.",
            "Genggam barbel sedikit lebih lebar dari bahu.",
            "Turunkan barbel sampai menyentuh bagian atas dada.",
            "Dorong kembali ke atas sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Kemiringan yang terlalu tajam memindahkan beban ke bahu, bukan ke dada bagian atas.",
    },
    {
        "id": "dumbbell_bench_press",
        "sumber_nama": "Dumbbell Bench Press",
        "nama": "Dumbbell Bench Press",
        "nama_id": "Menekan dumbel sambil berbaring",
        "pola_gerak": "dorong horizontal",
        "alias": ["dumbbell bench press", "dumbel bench press"],
        "langkah": [
            "Duduk di ujung bangku dengan dumbel di atas paha, lalu berbaring sambil mengangkat dumbel ke posisi dada.",
            "Tarik bahu ke belakang dan bawah, telapak kaki rata di lantai.",
            "Turunkan dumbel sampai sejajar dada dengan terkendali.",
            "Dorong dumbel ke atas sampai hampir bertemu di atas dada.",
        ],
        "poin_kunci": "Dumbel memberi rentang gerak lebih luas daripada barbel, jadi turunkan hanya sejauh yang masih nyaman untuk bahu.",
    },
    {
        "id": "incline_dumbbell_press",
        "sumber_nama": "Incline Dumbbell Press",
        "nama": "Incline Dumbbell Press",
        "nama_id": "Menekan dumbel pada bangku miring",
        "pola_gerak": "dorong horizontal ke atas",
        "alias": ["incline dumbbell press", "incline dumbbell bench press"],
        "langkah": [
            "Atur bangku pada kemiringan sekitar tiga puluh derajat.",
            "Duduk dengan dumbel di atas paha, lalu bersandar sambil membawa dumbel ke posisi bahu.",
            "Turunkan dumbel sampai sejajar dada bagian atas.",
            "Dorong kembali ke atas sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Jaga siku sedikit menyempit ke arah badan agar bahu tidak tertekan.",
    },
    {
        "id": "push_up",
        "sumber_nama": "Pushups",
        "nama": "Push-up",
        "nama_id": "Mendorong badan dari lantai",
        "pola_gerak": "dorong horizontal",
        "alias": ["push up", "pushup", "push ups", "pushups"],
        "langkah": [
            "Ambil posisi telungkup bertumpu pada telapak tangan dan ujung kaki, tangan sedikit lebih lebar dari bahu.",
            "Kencangkan perut dan bokong sehingga badan membentuk satu garis lurus dari kepala sampai tumit.",
            "Turunkan badan sampai dada hampir menyentuh lantai, siku menyudut sekitar empat puluh lima derajat.",
            "Dorong lantai sampai lengan hampir lurus tanpa membiarkan pinggul turun.",
        ],
        "poin_kunci": "Kalau pinggul melorot atau naik, kurangi jumlah repetisi atau lakukan dengan tangan di atas bangku.",
    },
    {
        "id": "machine_chest_press",
        "sumber_nama": "Machine Bench Press",
        "nama": "Machine Chest Press",
        "nama_id": "Menekan beban dada pada mesin",
        "pola_gerak": "dorong horizontal",
        "alias": ["machine chest press", "machine bench press", "chest press"],
        "langkah": [
            "Atur ketinggian kursi sampai pegangan sejajar dengan pertengahan dada.",
            "Duduk dengan punggung menempel penuh pada sandaran.",
            "Dorong pegangan ke depan sampai lengan hampir lurus.",
            "Kembalikan pegangan perlahan sampai terasa regangan di dada.",
        ],
        "poin_kunci": "Mesin memberi jalur gerak terkendali, sehingga cocok untuk pemula atau saat berlatih tanpa pengaman.",
    },
    {
        "id": "chest_fly",
        "sumber_nama": "Dumbbell Flyes",
        "nama": "Chest Fly",
        "nama_id": "Merentangkan dan merapatkan lengan",
        "pola_gerak": "isolasi dada",
        "alias": ["chest fly", "dumbbell fly", "dumbbell flyes", "chest flyes", "pec fly"],
        "langkah": [
            "Berbaring di bangku datar sambil memegang dumbel di atas dada dengan telapak saling berhadapan.",
            "Tekuk siku sedikit dan pertahankan sudut itu sepanjang gerakan.",
            "Rentangkan lengan ke samping sampai terasa regangan pada dada.",
            "Rapatkan kembali kedua dumbel di atas dada seperti sedang memeluk.",
        ],
        "poin_kunci": "Beban ringan sudah cukup; merentang terlalu dalam menekan sendi bahu.",
    },
    {
        "id": "overhead_press",
        "sumber_nama": "Standing Military Press",
        "nama": "Overhead Press",
        "nama_id": "Menekan barbel ke atas kepala",
        "pola_gerak": "dorong vertikal",
        "alias": ["overhead press", "military press", "standing press", "shoulder press", "ohp"],
        "langkah": [
            "Berdiri dengan kaki selebar pinggul, barbel bertumpu di depan bahu dengan genggaman selebar bahu.",
            "Kencangkan perut dan bokong agar punggung tidak melengkung.",
            "Dorong barbel lurus ke atas sambil sedikit menarik kepala ke belakang untuk memberi jalan.",
            "Kunci lengan di atas kepala, lalu turunkan barbel kembali ke depan bahu dengan terkendali.",
        ],
        "poin_kunci": "Kalau punggung bawah melengkung berlebihan, kurangi beban atau lakukan sambil duduk bersandar.",
    },
    {
        "id": "dumbbell_shoulder_press",
        "sumber_nama": "Seated Dumbbell Press",
        "nama": "Dumbbell Shoulder Press",
        "nama_id": "Menekan dumbel ke atas kepala",
        "pola_gerak": "dorong vertikal",
        "alias": ["dumbbell shoulder press", "seated dumbbell press", "dumbbell overhead press"],
        "langkah": [
            "Duduk di bangku bersandar tegak sambil memegang dumbel setinggi bahu.",
            "Hadapkan telapak tangan ke depan dan jaga siku sedikit di depan badan.",
            "Dorong dumbel ke atas sampai lengan hampir lurus.",
            "Turunkan dumbel perlahan sampai kembali setinggi bahu.",
        ],
        "poin_kunci": "Sandaran bangku membantu menjaga punggung tetap netral saat beban bertambah.",
    },
    {
        "id": "machine_shoulder_press",
        "sumber_nama": "Machine Shoulder (Military) Press",
        "nama": "Machine Shoulder Press",
        "nama_id": "Menekan beban bahu pada mesin",
        "pola_gerak": "dorong vertikal",
        "alias": ["machine shoulder press"],
        "langkah": [
            "Atur kursi sampai pegangan berada setinggi bahu.",
            "Duduk dengan punggung menempel pada sandaran.",
            "Dorong pegangan ke atas sampai lengan hampir lurus.",
            "Turunkan perlahan sampai pegangan kembali setinggi bahu.",
        ],
        "poin_kunci": "Pilihan yang aman ketika bahu masih dalam proses membiasakan diri dengan beban.",
    },
    {
        "id": "lateral_raise",
        "sumber_nama": "Side Lateral Raise",
        "nama": "Lateral Raise",
        "nama_id": "Mengangkat dumbel ke samping",
        "pola_gerak": "isolasi bahu samping",
        "alias": ["lateral raise", "side lateral raise", "lateral raises"],
        "langkah": [
            "Berdiri tegak dengan dumbel di kedua sisi badan dan siku sedikit ditekuk.",
            "Angkat kedua lengan ke samping sampai setinggi bahu.",
            "Tahan sebentar di posisi atas.",
            "Turunkan dumbel perlahan sampai kembali ke sisi badan.",
        ],
        "poin_kunci": "Jangan mengayun badan; kalau harus mengayun, bebannya terlalu berat.",
    },
    {
        "id": "rear_delt_fly",
        "sumber_nama": "Reverse Machine Flyes",
        "nama": "Rear Delt Fly",
        "nama_id": "Merentangkan lengan ke belakang",
        "pola_gerak": "isolasi bahu belakang",
        "alias": ["rear delt fly", "reverse fly", "reverse flyes", "rear delt raise"],
        "langkah": [
            "Duduk menghadap sandaran mesin dan pegang kedua pegangan di depan badan.",
            "Jaga siku sedikit ditekuk dan bahu turun.",
            "Rentangkan lengan ke belakang sampai sejajar bahu.",
            "Kembalikan pegangan perlahan ke posisi awal.",
        ],
        "poin_kunci": "Gerakan ini sering dipakai untuk menyeimbangkan latihan dada yang berlebih.",
    },
    {
        "id": "face_pull",
        "sumber_nama": "Face Pull",
        "nama": "Face Pull",
        "nama_id": "Menarik tali ke arah wajah",
        "pola_gerak": "tarik horizontal atas",
        "alias": ["face pull", "face pulls"],
        "langkah": [
            "Atur katrol setinggi wajah dan pasang tali, lalu pegang dengan kedua tangan.",
            "Mundur beberapa langkah sampai tali terasa tegang, kaki dibuka selebar pinggul.",
            "Tarik tali ke arah wajah sambil merentangkan kedua tangan ke samping.",
            "Kembalikan tali perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Fokus pada tulang belikat yang saling merapat, bukan pada besarnya beban.",
    },
    {
        "id": "dips",
        "sumber_nama": "Dips - Triceps Version",
        "nama": "Dips",
        "nama_id": "Menurunkan dan mengangkat badan di palang sejajar",
        "pola_gerak": "dorong vertikal ke bawah",
        "alias": ["triceps dips", "dips", "dip"],
        "langkah": [
            "Naik ke palang sejajar dengan lengan lurus menopang badan.",
            "Sedikit tekuk lutut dan silangkan pergelangan kaki.",
            "Turunkan badan dengan menekuk siku sampai lengan atas hampir sejajar lantai.",
            "Dorong kembali ke atas sampai lengan lurus.",
        ],
        "poin_kunci": "Turun terlalu dalam membebani sendi bahu; berhenti saat lengan atas sejajar lantai.",
    },
    {
        "id": "triceps_pushdown",
        "sumber_nama": "Triceps Pushdown",
        "nama": "Triceps Pushdown",
        "nama_id": "Menekan tali katrol ke bawah",
        "pola_gerak": "isolasi trisep",
        "alias": ["triceps pushdown", "tricep pushdown", "cable pushdown", "pushdown"],
        "langkah": [
            "Berdiri menghadap mesin katrol atas dan pegang batang atau tali.",
            "Rapatkan siku ke sisi badan dan condongkan badan sedikit ke depan.",
            "Luruskan siku untuk menekan beban ke bawah.",
            "Kembalikan perlahan sampai lengan bawah sejajar lantai.",
        ],
        "poin_kunci": "Siku harus tetap di sisi badan; siku yang bergerak memindahkan kerja ke bahu.",
    },
    {
        "id": "overhead_triceps_extension",
        "sumber_nama": "Standing Dumbbell Triceps Extension",
        "nama": "Overhead Triceps Extension",
        "nama_id": "Meluruskan lengan di atas kepala",
        "pola_gerak": "isolasi trisep",
        "alias": ["overhead triceps extension", "triceps extension", "tricep extension"],
        "langkah": [
            "Berdiri tegak sambil memegang satu dumbel dengan kedua tangan di atas kepala.",
            "Jaga siku tetap rapat dan mengarah ke depan.",
            "Turunkan dumbel ke belakang kepala dengan menekuk siku.",
            "Luruskan siku untuk mengangkat dumbel kembali ke atas.",
        ],
        "poin_kunci": "Kencangkan perut agar punggung bawah tidak melengkung saat lengan di atas kepala.",
    },
    # ----------------------------------------------------------- TARIK BAGIAN ATAS
    {
        "id": "pull_up",
        "sumber_nama": "Pullups",
        "nama": "Pull-up",
        "nama_id": "Menarik badan ke palang dengan telapak menghadap depan",
        "pola_gerak": "tarik vertikal",
        "alias": ["pull up", "pullup", "pull ups", "pullups"],
        "langkah": [
            "Gantung pada palang dengan genggaman selebar bahu, telapak tangan menghadap ke depan.",
            "Turunkan bahu menjauhi telinga dan kencangkan perut.",
            "Tarik badan ke atas sampai dagu melewati palang.",
            "Turunkan badan perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Kalau belum sanggup, pakai karet pembantu atau lakukan versi turun perlahan saja.",
    },
    {
        "id": "chin_up",
        "sumber_nama": "Chin-Up",
        "nama": "Chin-up",
        "nama_id": "Menarik badan ke palang dengan telapak menghadap badan",
        "pola_gerak": "tarik vertikal",
        "alias": ["chin up", "chinup", "chin ups"],
        "langkah": [
            "Gantung pada palang dengan telapak tangan menghadap badan, selebar bahu.",
            "Kencangkan perut dan turunkan bahu.",
            "Tarik badan ke atas sampai dagu melewati palang.",
            "Turunkan badan perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Genggaman menghadap badan melibatkan bisep lebih banyak, biasanya terasa lebih ringan daripada pull-up.",
    },
    {
        "id": "lat_pulldown",
        "sumber_nama": "Wide-Grip Lat Pulldown",
        "nama": "Lat Pulldown",
        "nama_id": "Menarik batang katrol ke dada",
        "pola_gerak": "tarik vertikal",
        "alias": ["lat pulldown", "lat pull down", "pulldown"],
        "langkah": [
            "Duduk di mesin dan atur bantalan paha sampai menahan tubuh dengan mantap.",
            "Genggam batang lebih lebar dari bahu.",
            "Tarik batang ke arah dada bagian atas sambil merapatkan tulang belikat.",
            "Kembalikan batang perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Tarik ke depan dada, bukan ke belakang leher, agar bahu tidak tertekan.",
    },
    {
        "id": "barbell_row",
        "sumber_nama": "Bent Over Barbell Row",
        "nama": "Barbell Row",
        "nama_id": "Menarik barbel dalam posisi membungkuk",
        "pola_gerak": "tarik horizontal",
        "alias": ["bent over barbell row", "barbell row", "bent over row"],
        "langkah": [
            "Berdiri memegang barbel dengan genggaman selebar bahu.",
            "Dorong pinggul ke belakang sampai badan condong sekitar empat puluh lima derajat, punggung tetap lurus.",
            "Tarik barbel ke arah perut bagian bawah sambil merapatkan tulang belikat.",
            "Turunkan barbel perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Jaga punggung tetap lurus; gerakan ini paling sering salah karena punggung ikut naik turun.",
    },
    {
        "id": "dumbbell_row",
        "sumber_nama": "One-Arm Dumbbell Row",
        "nama": "One-Arm Dumbbell Row",
        "nama_id": "Menarik dumbel satu tangan bertumpu bangku",
        "pola_gerak": "tarik horizontal",
        "alias": ["one arm dumbbell row", "single arm row", "dumbbell row"],
        "langkah": [
            "Letakkan satu lutut dan satu telapak tangan di atas bangku, kaki yang lain menapak di lantai.",
            "Pegang dumbel dengan tangan yang bebas, biarkan lengan menggantung lurus.",
            "Tarik dumbel ke arah pinggul sambil menjaga punggung tetap datar.",
            "Turunkan dumbel perlahan sampai lengan lurus kembali, lalu ganti sisi setelah semua repetisi selesai.",
        ],
        "poin_kunci": "Badan tidak boleh ikut berputar saat menarik; jaga bahu tetap sejajar.",
    },
    {
        "id": "seated_cable_row",
        "sumber_nama": "Seated Cable Rows",
        "nama": "Seated Cable Row",
        "nama_id": "Menarik pegangan katrol sambil duduk",
        "pola_gerak": "tarik horizontal",
        "alias": ["seated cable row", "seated row", "cable row"],
        "langkah": [
            "Duduk menghadap mesin, letakkan kaki pada pijakan dengan lutut sedikit ditekuk.",
            "Pegang gagang dan tegakkan badan sampai punggung lurus.",
            "Tarik gagang ke arah perut sambil merapatkan tulang belikat.",
            "Kembalikan gagang perlahan sampai lengan hampir lurus tanpa membungkuk.",
        ],
        "poin_kunci": "Badan tetap tegak; jangan mengayun ke belakang untuk membantu tarikan.",
    },
    {
        "id": "shrug",
        "sumber_nama": "Barbell Shrug",
        "nama": "Shrug",
        "nama_id": "Mengangkat bahu ke arah telinga",
        "pola_gerak": "isolasi trapezius",
        "alias": ["barbell shrug", "shrug", "shrugs"],
        "langkah": [
            "Berdiri tegak memegang barbel atau dumbel di depan paha.",
            "Jaga lengan tetap lurus sepanjang gerakan.",
            "Angkat bahu lurus ke atas ke arah telinga.",
            "Turunkan bahu perlahan sampai kembali ke posisi awal.",
        ],
        "poin_kunci": "Angkat lurus ke atas; memutar bahu tidak menambah manfaat dan menambah tekanan pada leher.",
    },
    {
        "id": "barbell_curl",
        "sumber_nama": "Barbell Curl",
        "nama": "Barbell Curl",
        "nama_id": "Menekuk siku mengangkat barbel",
        "pola_gerak": "isolasi bisep",
        "alias": ["barbell curl", "biceps curl", "bicep curl"],
        "langkah": [
            "Berdiri tegak memegang barbel selebar bahu dengan telapak menghadap ke depan.",
            "Rapatkan siku ke sisi badan.",
            "Tekuk siku untuk mengangkat barbel sampai setinggi dada.",
            "Turunkan barbel perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Badan tidak boleh mengayun; kalau mengayun, kurangi bebannya.",
    },
    {
        "id": "dumbbell_curl",
        "sumber_nama": "Dumbbell Bicep Curl",
        "nama": "Dumbbell Curl",
        "nama_id": "Menekuk siku mengangkat dumbel",
        "pola_gerak": "isolasi bisep",
        "alias": ["dumbbell curl", "dumbbell bicep curl", "dumbbell biceps curl"],
        "langkah": [
            "Berdiri tegak dengan dumbel di kedua sisi badan, telapak menghadap ke depan.",
            "Rapatkan siku ke sisi badan.",
            "Tekuk siku mengangkat dumbel sampai setinggi bahu.",
            "Turunkan perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Bisa dikerjakan bergantian kiri-kanan agar tempo lebih terkendali.",
    },
    {
        "id": "hammer_curl",
        "sumber_nama": "Hammer Curls",
        "nama": "Hammer Curl",
        "nama_id": "Curl dengan telapak saling berhadapan",
        "pola_gerak": "isolasi bisep dan lengan bawah",
        "alias": ["hammer curl", "hammer curls"],
        "langkah": [
            "Berdiri tegak dengan dumbel di kedua sisi badan, telapak tangan saling berhadapan.",
            "Rapatkan siku ke sisi badan.",
            "Tekuk siku mengangkat dumbel tanpa memutar pergelangan tangan.",
            "Turunkan perlahan sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Posisi telapak seperti memegang palu memberi tekanan lebih pada lengan bawah.",
    },
    {
        "id": "external_rotation",
        "sumber_nama": "External Rotation",
        "nama": "Shoulder External Rotation",
        "nama_id": "Memutar lengan ke luar",
        "pola_gerak": "penguat rotator bahu",
        "alias": ["external rotation", "shoulder external rotation", "rotasi eksternal bahu"],
        "langkah": [
            "Berbaring menyamping dengan lengan atas menempel di sisi badan dan siku ditekuk sembilan puluh derajat.",
            "Pegang dumbel ringan dengan tangan yang berada di atas.",
            "Putar lengan bawah ke atas sampai mengarah ke langit-langit, siku tetap menempel di sisi badan.",
            "Turunkan perlahan sampai kembali ke posisi awal.",
        ],
        "poin_kunci": "Gunakan beban sangat ringan; gerakan ini melatih otot kecil penstabil bahu.",
    },
    {
        "id": "wrist_curl",
        "sumber_nama": "Palms-Up Barbell Wrist Curl Over A Bench",
        "nama": "Wrist Curl",
        "nama_id": "Menekuk pergelangan tangan melawan beban",
        "pola_gerak": "penguat lengan bawah",
        "alias": ["wrist curl", "wrist curls"],
        "langkah": [
            "Duduk dan sandarkan lengan bawah di atas paha atau bangku, telapak menghadap ke atas.",
            "Pegang barbel ringan, biarkan pergelangan tangan menggantung di luar tumpuan.",
            "Tekuk pergelangan tangan ke atas semampunya.",
            "Turunkan perlahan sampai pergelangan tangan kembali menggantung.",
        ],
        "poin_kunci": "Beban ringan dan repetisi lebih banyak biasanya lebih nyaman untuk siku dan pergelangan tangan.",
    },
    # ------------------------------------------------------------------------ INTI
    {
        "id": "plank",
        "sumber_nama": "Plank",
        "nama": "Plank",
        "nama_id": "Menahan posisi badan lurus bertumpu siku",
        "pola_gerak": "penstabil batang tubuh",
        "alias": ["plank", "planking"],
        "langkah": [
            "Ambil posisi telungkup bertumpu pada kedua siku dan ujung kaki.",
            "Letakkan siku tepat di bawah bahu.",
            "Kencangkan perut dan bokong sampai badan lurus dari kepala hingga tumit.",
            "Tahan posisi itu sesuai waktu yang ditentukan sambil bernapas normal.",
        ],
        "poin_kunci": "Kalau pinggul mulai turun, hentikan hitungan; menahan lebih lama dengan posisi rusak tidak menambah manfaat.",
    },
    {
        "id": "side_plank",
        "sumber_nama": "Side Bridge",
        "nama": "Side Plank",
        "nama_id": "Menahan posisi menyamping bertumpu satu siku",
        "pola_gerak": "penstabil batang tubuh",
        "alias": ["side plank", "side bridge"],
        "langkah": [
            "Berbaring menyamping bertumpu pada satu siku yang berada tepat di bawah bahu.",
            "Tumpuk kedua kaki dan luruskan badan.",
            "Angkat pinggul sampai badan lurus dari kepala sampai kaki.",
            "Tahan sesuai waktu yang ditentukan, lalu ganti sisi.",
        ],
        "poin_kunci": "Jaga pinggul tetap terangkat dan badan tidak berputar ke depan atau belakang.",
    },
    {
        "id": "cable_crunch",
        "sumber_nama": "Cable Crunch",
        "nama": "Cable Crunch",
        "nama_id": "Melipat badan melawan tarikan katrol",
        "pola_gerak": "isolasi perut",
        "alias": ["cable crunch"],
        "langkah": [
            "Berlutut menghadap mesin katrol atas sambil memegang tali di samping kepala.",
            "Tekuk pinggul sedikit dan pertahankan posisi itu.",
            "Lipat badan ke bawah dengan membulatkan tulang punggung atas, bukan dengan menekuk pinggul.",
            "Kembali ke posisi awal perlahan melawan tarikan beban.",
        ],
        "poin_kunci": "Pinggul harus tetap di tempat; kalau pinggul ikut bergerak, yang bekerja adalah otot pinggul, bukan perut.",
    },
    {
        "id": "hanging_leg_raise",
        "sumber_nama": "Hanging Leg Raise",
        "nama": "Hanging Leg Raise",
        "nama_id": "Mengangkat kaki sambil bergantung",
        "pola_gerak": "isolasi perut",
        "alias": ["hanging leg raise", "hanging knee raise"],
        "langkah": [
            "Gantung pada palang dengan genggaman selebar bahu.",
            "Kencangkan perut dan hentikan ayunan badan.",
            "Angkat kedua kaki ke depan sampai paha minimal sejajar lantai.",
            "Turunkan kaki perlahan tanpa mengayun.",
        ],
        "poin_kunci": "Kalau masih berat, tekuk lutut terlebih dahulu sebelum berlatih dengan kaki lurus.",
    },
    {
        "id": "crunch",
        "sumber_nama": "Crunches",
        "nama": "Crunch",
        "nama_id": "Melipat badan tanpa alat",
        "pola_gerak": "isolasi perut",
        "alias": ["crunch", "crunches"],
        "langkah": [
            "Berbaring telentang dengan lutut ditekuk dan telapak kaki rata di lantai.",
            "Letakkan tangan di samping kepala tanpa menarik leher.",
            "Angkat bahu dari lantai dengan melipat tulang punggung atas.",
            "Turunkan bahu perlahan sampai hampir menyentuh lantai.",
        ],
        "poin_kunci": "Leher tidak boleh ditarik dengan tangan; jaga dagu berjarak kira-kira satu kepalan dari dada.",
    },
    {
        "id": "bench_dips",
        "sumber_nama": "Bench Dips",
        "nama": "Bench Dips",
        "nama_id": "Menurunkan badan bertumpu bangku",
        "pola_gerak": "dorong vertikal ke bawah",
        "alias": ["bench dips", "bench dip"],
        "langkah": [
            "Duduk di tepi bangku, letakkan kedua telapak tangan di sisi pinggul.",
            "Geser pinggul keluar dari bangku dan luruskan kaki ke depan.",
            "Turunkan badan dengan menekuk siku sampai lengan atas hampir sejajar lantai.",
            "Dorong kembali ke atas sampai lengan hampir lurus.",
        ],
        "poin_kunci": "Versi yang lebih ringan daripada dips di palang sejajar, cocok untuk pemula.",
    },
]
